### ISSUE TITLE
Question about NewComponent and multiple invocations of the model constructor vmCreator per component instance

### ISSUE THREAD

**Issue by theclapp** [oskca/gopherjs-vue#1]
In component.go, NewComponent has a closure called vmfn, which calls the vmCreator function every third time it (vmfn) is invoked.  The intent seems to be call vmCreator once for each instance of the given component.

As near as I can tell, vmfn is called _four_ times per component.

Is there a mismatch going on somewhere, or have I missed something, or what?

Thanks for this package!

**Comment by theclapp** [comment]
vmCreator is called twice in the "init" lifecycle event, and then twice in Vue.prototype._initData, once as dataFn() and once as this._runtimeData().

**Comment by oskca** [comment]
yes, the multiple invocation of `vmfn` is on purpose for  `vue.GetVM` to work in components
