### ISSUE TITLE
Infernojs Bindings

### ISSUE THREAD

**Issue by sebastianmacias** [oskca/gopherjs-vue#5]
Not the right place to ask but since there is no pm in github, I'll ask here.

I see you are the maintainer of several gopherjs bindings. Have you consider implementing the [Inferno](https://infernojs.org) bindings for gopherjs?

**Comment by oskca** [comment]
Well, I do not quite understand the `React` style for the Web. By the first look  `Inferno.js` and `React.js` are too coupled with JS and HTML by using HTML directly in JS, which is not quite easy for a GopherJs binding (or a third language biding) IMHO.

BTW: if you want to use `GO` in web, I suggest you use [vue.js](vuejs.org) with [gopherjs-vue](github.com/oskca/gopherjs-vue) which has good separation between JS and HTML. :smile:
